name: approve_and_label
on: 
  pull_request:
    types: [opened, reopened]
    

jobs:
  parse_dependabot_pr:
    runs-on: ubuntu-latest
    name: Parse Dependabot PR title
    outputs:
      dependency_name: ${{ steps.parse_dependabot_pr.outputs.dependency_name }}
      update_type: ${{ steps.parse_dependabot_pr.outputs.update_type }}
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Parse Dependabot PR title
        id: parse_dependabot_pr
        uses: ./.github/actions/parse_dependabot_pr
        with:
          pr_title: ${{ github.event.pull_request.title }}
  approve_and_label:
    runs-on: ubuntu-latest
    needs: parse_dependabot_pr
    name: Approve and label
    if: |
        github.actor == 'dependabot[bot]' &&
        github.event_name == 'pull_request' &&
        (startsWith(needs.parse_dependabot_pr.outputs.dependency_name, 'Endjin') ||
        startsWith(needs.parse_dependabot_pr.outputs.dependency_name, 'Corvus') ||
        startsWith(needs.parse_dependabot_pr.outputs.dependency_name, 'Menes') ||
        startsWith(needs.parse_dependabot_pr.outputs.dependency_name, 'Marain') ||
        startsWith(needs.parse_dependabot_pr.outputs.dependency_name, 'dependency-playground')) &&
        (needs.parse_dependabot_pr.outputs.update_type == 'minor' || needs.parse_dependabot_pr.outputs.update_type == 'patch')
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Approve pull request
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ steps.generate_token.outputs.token }}'
          event: APPROVE
          body: 'Thank you dependabot 🎊'
      - name: 'Label with "autosquash"'
        env: 
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        uses: actions/github-script@v2
        with:
          github-token: '${{ steps.generate_token.outputs.token }}'
          script: |
            await github.issues.addLabels({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              labels: ['autosquash']
            })
