on: 
  workflow_dispatch:
jobs:
  gitversion_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: Install GitVersion
      # if: |
      #     steps.watch_dependabot_prs.outputs.is_complete == 'True'
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'
    
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
    
    - run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "SemVer: ${{ steps.gitversion.outputs.semver }}"
      name: gitversion-output

    - name: Bump version and push tag
      id: tag
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: false
        tag_prefix: v
        dry_run: true

    - run: |
        echo "new_tag: ${{ steps.tag.outputs.new_tag }}"
        echo "new_version : ${{ steps.tag.outputs.new_version  }}"
        echo "previous_tag : ${{ steps.tag.outputs.previous_tag  }}"
        echo "changelog : ${{ steps.tag.outputs.changelog  }}"
      name: tag-output